# Data Loader Function Test Notebook

This notebook tests all functions in src/data_loader.py using real CSV files from Dataset/.
Outputs are printed in each cell.

In [1]:
from pathlib import Path
import sys

project_root = Path.cwd().parent if Path.cwd().name == "tests" else Path.cwd()
src_path = project_root / "src"
dataset_dir = project_root / "Dataset"
train_csv = dataset_dir / "train.csv"
test_csv = dataset_dir / "test.csv"

if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

from data_loader import load_csv, load_train_data, load_test_data, load_train_test_data

print("Project root:", project_root)
print("Dataset dir :", dataset_dir)
print("train.csv exists:", train_csv.exists())
print("test.csv exists :", test_csv.exists())

Project root: c:\Users\POOJA\OneDrive\Desktop\project
Dataset dir : c:\Users\POOJA\OneDrive\Desktop\project\Dataset
train.csv exists: True
test.csv exists : True

## 1. Test load_csv with train.csv

In [2]:
try:
    train_df = load_csv(train_csv)
    print("load_csv(train.csv) PASSED")
    print("Shape:", train_df.shape)
    print("Columns:", list(train_df.columns))
    display(train_df.head(2))
except Exception as e:
    print("load_csv(train.csv) FAILED")
    print(type(e).__name__, str(e))

load_csv(train.csv) PASSED
Shape: (1986, 2)
Columns: ['text', 'label']

                                                text         label
0  ENGINEERING CONSULTANT Professional Summary To...    CONSULTANT
1  CARPENTER Summary Carpenter Foreman Position w...  CONSTRUCTION

## 2. Test load_csv with test.csv

In [3]:
try:
    test_df = load_csv(test_csv)
    print("load_csv(test.csv) PASSED")
    print("Shape:", test_df.shape)
    print("Columns:", list(test_df.columns))
    display(test_df.head(2))
except Exception as e:
    print("load_csv(test.csv) FAILED")
    print(type(e).__name__, str(e))

load_csv(test.csv) PASSED
Shape: (497, 2)
Columns: ['text', 'label']

                                                text         label
0  OWNER/ FABRICATOR/ WELDER Experience Owner/ Fa...  CONSTRUCTION
1  SR. ESTIMATOR-BAS CONSTRUCTION SALES Summary 9...  CONSTRUCTION

## 3. Test load_train_data

In [4]:
try:
    train_df2 = load_train_data(dataset_dir)
    print("load_train_data PASSED")
    print("Shape:", train_df2.shape)
    print("Columns:", list(train_df2.columns))
except Exception as e:
    print("load_train_data FAILED")
    print(type(e).__name__, str(e))

load_train_data PASSED
Shape: (1986, 2)
Columns: ['text', 'label']

## 4. Test load_test_data

In [5]:
try:
    test_df2 = load_test_data(dataset_dir)
    print("load_test_data PASSED")
    print("Shape:", test_df2.shape)
    print("Columns:", list(test_df2.columns))
except Exception as e:
    print("load_test_data FAILED")
    print(type(e).__name__, str(e))

load_test_data PASSED
Shape: (497, 2)
Columns: ['text', 'label']

## 5. Test load_train_test_data

In [6]:
try:
    train_df3, test_df3 = load_train_test_data(dataset_dir)
    print("load_train_test_data PASSED")
    print("Train shape:", train_df3.shape)
    print("Test shape :", test_df3.shape)
except Exception as e:
    print("load_train_test_data FAILED")
    print(type(e).__name__, str(e))

load_train_test_data PASSED
Train shape: (1986, 2)
Test shape : (497, 2)